package wang.relish.accumulation.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wang.relish.accumulation.entity.User;
import wang.relish.accumulation.entity.Record;
import wang.relish.accumulation.entity.Goal;

import wang.relish.accumulation.greendao.UserDao;
import wang.relish.accumulation.greendao.RecordDao;
import wang.relish.accumulation.greendao.GoalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig recordDaoConfig;
    private final DaoConfig goalDaoConfig;

    private final UserDao userDao;
    private final RecordDao recordDao;
    private final GoalDao goalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        goalDaoConfig = daoConfigMap.get(GoalDao.class).clone();
        goalDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);
        goalDao = new GoalDao(goalDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Record.class, recordDao);
        registerDao(Goal.class, goalDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
        goalDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public GoalDao getGoalDao() {
        return goalDao;
    }

}
